//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Путешествуй_по_России
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Hotel = new HashSet<Hotel>();
            this.Type = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public int TicketCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImagePreview { get; set; }
        public decimal Price { get; set; }
        public bool IsActual { get; set; }

        /// <summary>
        /// Свойство для получения пути к изображению
        /// </summary>
        public string ImagePath
        {
            set
            {

            }
            get
            {
                return "/Resources/Photo/" + this.Name + ".jpg";
            }
        }

        public string FullViewPrice
        {
            get
            {
                return (int) this.Price + " РУБ";
            }
        }

        public string FullTicketCount
        {
            set
            {

            }
            get
            {
                return "Количество билетов: " + this.TicketCount;
            }
        }

        public string State
        {
            get
            {
                return IsActual? "Актуален" : "Не актуален";
            }
        }

        public SolidColorBrush solidColorBrush
        {           
            get
            {
                return IsActual ? Brushes.Green : Brushes.Red;
            }
          
        }

[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Type { get; set; }
    }
}
